backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "content/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Castellano", name: "body", widget: "markdown"}
      - {label: "English", name: "body_eng", widget: "markdown"}
  - name: "feed" # Used in routes, e.g., /admin/collections/blog
    label: "Feed" # Used in the UI
    folder: "content/feed" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Castellano", name: "body", widget: "markdown"}
      - {label: "Title", name: "title_eng", widget: "string"}
      - {label: "English", name: "body_eng", widget: "markdown"}
  - name: "sensiblog" # Used in routes, e.g., /admin/collections/blog
    label: "Sensiblog" # Used in the UI
    folder: "content/sensiblog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Castellano", name: "body", widget: "markdown"}
      - {label: "Title", name: "title_eng", widget: "string"}
      - {label: "English", name: "body_eng", widget: "markdown"}
  - name: "posible" # Used in routes, e.g., /admin/collections/blog
    label: "Posible" # Used in the UI
    folder: "content/posible" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Stock", name: "stock", widget: "number"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Castellano", name: "body", widget: "markdown"}
      - {label: "Title", name: "title_eng", widget: "string"}
      - {label: "English", name: "body_eng", widget: "markdown"}
  - name: "modals" # Used in routes, e.g., /admin/collections/blog
    label: "Modals" # Used in the UI
    folder: "content/modals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Castellano", name: "body", widget: "markdown"}
      - {label: "English", name: "body_eng", widget: "markdown"}  